apiVersion: apps/v1
Kind: deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app

spec:
  replicas: 2
  selector:
    matchLables:
      app: nginx-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
       - name: nginx
         image: acrpracticedev.azurecr.io/my-nginx-app:4
         ports:
           - containerPort: 80
